# Generated by Django 4.2.3 on 2023-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_create_at_record_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='state',
            field=models.CharField(default='Delhi', max_length=50),
            preserve_default=False,
        ),
    ]
